version: "3.9"
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=metheuser
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"